services:
  db:
    image: paradedb/paradedb:latest-pg16
    container_name: lol_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: lol_lore
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  neo4j_db:
    image: neo4j:5
    container_name: lol_graph_db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/secretpassword
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

volumes:
  pgdata:
  neo4j_data:
